<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var array $config Require keys "root", "iiifResourceUri" and "configUri".
 *
 * @link https://github.com/UniversalViewer/universalviewer/wiki/V3
 */
$config['id'] = $config['id'] ?? 'uv';
$configJson = json_encode($config, 448);
$script = <<<JS
if (typeof uv === 'undefined') {
    var uv = [];
}
if (location.protocol !== 'http:') {
   url = {$configJson};
   iiifuri = url['iiifResourceUri'];
   updatedURL = iiifuri.replace(/^http:\/\//i, 'https://');
   url['iiifResourceUri']=updatedURL;
   uv.push(url);
}else{
	uv.push($configJson);
}


JS;

$this->headScript()
    ->appendFile($this->assetUrl('js/universal-viewer.js', 'UniversalViewer'), 'text/javascript', ['defer' => 'defer'])
    ->appendScript($script);
?>
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<div id="<?= $config['id'] ?>" class="universal-viewer viewer"></div>
